plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
github:
  is_project_pages: false

theme: jekyll-theme-cayman
title: AYLUS Volunteers - by AYLUS Irvine
description: Learn how to install the beta on your Apple devices.
